version: '3'

tasks:
  build:
    desc: Build the mock-fps server binary
    cmds:
      - go build -o bin/mock-fps ./cmd/server

  run:
    desc: Build and run the server
    deps: [build]
    cmds:
      - ./bin/mock-fps

  test:
    desc: Run all tests with race detector
    cmds:
      - go test -race ./...

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -rf bin/
